---
title: "ds2_final"
author: "Maisie Sun"
date: "2023-04-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret) 
library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)
library(olsrr)
library(splines)
library(pdp)
library(mgcv)
library(earth)
library(ggcorrplot)
library(corrplot)
library(ggpubr)
library(MASS)
library(mlbench)
library(pROC)
library(klaR)
library(rpart)
library(randomForest)
library(ranger)
library(gbm)
library(pdp)
library(pROC)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Merge data
```{r data_merging}
data_2101 <- 
  read_csv("./data/2101_data.csv") %>%
  janitor::clean_names() %>%
  na.omit()

data_6360 <-
  read_csv("./data/6360_data.csv") %>%
  janitor::clean_names() %>%
  na.omit()

data <- rbind(data_2101, data_6360) %>%
  unique() %>%
  mutate(gender = as.factor(gender),
         smoking = as.factor(smoking),
         race = as.factor(race),
         hypertension = as.factor(hypertension),
         diabetes = as.factor(diabetes),
         vaccine = as.factor(vaccine),
         severity = as.factor(severity),
         study = as.factor(study))
```

# Create binary outcome
```{r}
data_binary <-
  data %>%
  mutate(
    recovery_time = case_when(recovery_time > 30 ~ "long",
                                     TRUE ~ "short")) %>%
  mutate(
    recovery_time = as.factor(recovery_time))
```

# Data partition: training and testing datasets
```{r data, warning=FALSE}
set.seed(6360) 
trRows_binary <- createDataPartition(data_binary$recovery_time,
                              p = .80,
                              list = F)

# training data
trainData_binary <- data_binary[trRows_binary, ]
trainData_matrix_binary <-
  model.matrix(recovery_time~.,data_binary)[trRows_binary, ]
train_x_binary <- model.matrix(recovery_time~.,data_binary)[trRows_binary,-1]
train_y_binary <- data_binary$recovery_time[trRows_binary]

# test data
testData_binary <- data_binary[-trRows_binary, ]
testData_matrix_binary <-
  model.matrix(recovery_time~.,data_binary)[-trRows_binary,]
test_x_binary <- model.matrix(recovery_time~.,data_binary)[-trRows_binary,-1]
test_y_binary <- data_binary$recovery_time[-trRows_binary]

ctrl_binary <- trainControl(method = "repeatedcv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE)

# str(data)
```

# Logistic Regression
```{r}
set.seed(6360) 

# contrasts(data$recovery_time)

model.glm.binary <- train(train_x_binary, 
                          train_y_binary,
                          method = "glm",
                          metric = "ROC",
                          trControl = ctrl_binary)

pred_binary <- predict(model.glm.binary, newdata = test_x_binary, 
                       type = "prob")[,1]
pred2_binary <- rep("short", length(pred_binary))
pred2_binary[pred_binary>0.5] = "long"

#mean(pred2_binary != testData_binary$recovery_time)
```

# Penalized Logistic Regression
```{r}
glmnGrid <- expand.grid(.alpha = seq(0, 1, length = 21),
                        .lambda = exp(seq(-8, -1, length = 50)))

ctrl <- trainControl(method = "repeatedcv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE)

set.seed(6360)
model.glmn.binary <- train(train_x_binary,
                    train_y_binary,
                    method = "glmnet",
                    tuneGrid = glmnGrid,
                    metric = "ROC",
                    trControl = ctrl)

model.glmn.binary$bestTune

myCol<- rainbow(25)
myPar <- list(superpose.symbol = list(col = myCol),
              superpose.line = list(col = myCol))

plot(model.glmn.binary, par.settings = myPar, xTrans = function(x) log(x))
```

# GAM
```{r}
set.seed(6360) 

model.gam.binary <- train(train_x_binary,
                   train_y_binary,
                   method = "gam",
                   metric = "ROC",
                   trControl = ctrl_binary)
```

# MARS
```{r}
set.seed(6360) 

model.mars.binary <- train(train_x_binary,
                           train_y_binary,
                           method = "earth",
                           tuneGrid = expand.grid(degree = 1:4,
                                                  nprune = 2:20),
                           metric = "ROC",
                           trControl = ctrl_binary)

plot(model.mars.binary)
```

# LDA
```{r}
set.seed(6360) 

model.lda.binary <- train(train_x_binary,
                          train_y_binary,
                          method = "lda",
                          metric = "ROC",
                          trControl = ctrl_binary)
```

# QDA
```{r}
set.seed(6360) 

model.qda.binary <- train(train_x_binary,
                          train_y_binary,
                          method = "qda",
                          metric = "ROC",
                          trControl = ctrl_binary)
```

# Naive Bayes
```{r}
nbGrid <- expand.grid(usekernel = c(FALSE,TRUE),
                      fL = 1,
                      adjust = seq(.2, 3, by = .2))

set.seed(6360)

model.nb.binary <- train(train_x_binary,
                         train_y_binary,
                         method = "nb",
                         tuneGrid = nbGrid,
                         metric = "ROC",
                         trControl = ctrl_binary)

plot(model.nb.binary)
```

# Classification Tree - rpart
```{r}
set.seed(6360)

# Using caret
rpart.fit.binary <- train(recovery_time ~ . ,
                          data_binary,
                          subset = trRows_binary,
                          method = "rpart",
                          tuneGrid = data.frame(
                            cp = exp(seq(-6,-3, len = 50))),
                          trControl = ctrl_binary,
                          metric = "ROC")

ggplot(rpart.fit.binary, highlight = TRUE)

rpart.plot::rpart.plot(rpart.fit.binary$finalModel)
```

# Classification Tree - ctree
```{r}
set.seed(6360)

# Using caret
ctree.fit.binary <- train(recovery_time ~ . , 
                          data_binary,
                          subset = trRows_binary,
                          method = "ctree",
                          tuneGrid = data.frame(
                            mincriterion = 1-exp(seq(-2, -1, length = 50))),
                          metric = "ROC",
                          trControl = ctrl_binary)

ggplot(ctree.fit.binary, highlight = TRUE)

plot(ctree.fit.binary$finalModel)
```

# Bagging and random forests
```{r}
# Using caret
rf.grid.binary <- expand.grid(mtry = 1:8,
                              splitrule = "gini",
                              min.node.size = seq(from = 2, to = 10, by = 2))

set.seed(6360)

rf.fit.binary <- train(recovery_time ~ . ,
                       data_binary,
                       subset = trRows_binary,
                       method = "ranger",
                       tuneGrid = rf.grid.binary,
                       metric = "ROC",
                       trControl = ctrl_binary)

ggplot(rf.fit.binary, highlight = TRUE)
```

# Boosting
```{r}
gbmA.grid.binary <- expand.grid(n.trees = c(2000,3000,4000,5000),
                                interaction.depth = 1:6,
                                shrinkage = c(0.0005,0.001,0.002),
                                n.minobsinnode = 1)

set.seed(6360)

gbmA.fit.binary <- train(recovery_time ~ . ,
                         data_binary,
                         subset = trRows_binary,
                         tuneGrid = gbmA.grid.binary,
                         trControl = ctrl_binary,
                         method = "gbm",
                         distribution = "adaboost",
                         metric = "ROC",
                         verbose = FALSE)

ggplot(gbmA.fit.binary, highlight = TRUE)
```

# SVM
```{r}
set.seed(6360)

svmGrid.binary <- expand.grid(C = seq(0.1, 10, by = 0.5),
                       sigma = seq(0.1, 1, by = 0.1))

svm.model.binary <- train(x = train_x_binary,
                          y = train_y_binary,
                          method = "svmRadial",
                          tuneGrid = svmGrid.binary,
                          metric = "ROC",
                          trControl = ctrl_binary)

plot(svm.model.binary)
```

# Resample
```{r}
res <- resamples(list(GLM = model.glm.binary,
                      GLMNET = model.glmn,
                      GAM = model.gam,
                      MARS = model.mars,
                      LDA = model.lda.binary,
                      QDA = model.qda.binary,
                      NB = model.nb.binary,
                      RPART = rpart.fit.binary,
                      CTREE = ctree.fit.binary,
                      RF = rf.fit.binary,
                      GBM = gbmA.fit.binary,
                      SVM = svm.model.binary))

summary(res)
```

